### PR TITLE
This is probably your password

### PR DESCRIPTION
**Pull request by dionyziz**

### CODE REVIEW

**Comment by OrfeasLitos** [comment]
I was also surprised by this, but the user name goes there.

**Comment by cnasikas** [comment]
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by dionyziz** [comment]
So?

**Comment by OrfeasLitos** [comment]
I tried both and both work.

Keep in mind that the postgres role has the same name as the user I use to run the api and the app.

**Comment by dionyziz** [comment]
You just haven't set up a password.

**Comment by dionyziz** [comment]
Should this be merged or is there some objection?

**Comment by cnasikas** [comment]
It's ok by me

**Comment by OrfeasLitos** [comment]
I approve as well

**Pull request merged**
