### PR TITLE
Simplify and automate installation

### PR DESCRIPTION
**Pull request by OrfeasLitos**

### CODE REVIEW

**Comment by OrfeasLitos** [comment]
Fixes #17

**Review by cnasikas — CHANGES_REQUESTED** [review]
I don't think that the `createdb` command should be a part of the installation script. The repo is agnostic to database management system. The script should run to any DBMS. 

Also the name of the database doesn't matter. The following command should change to ` DB_URI=postgres://your_username:your_username@localhost/your_database`

**Comment by OrfeasLitos** [comment]
I'll add a note saying that any db works, but we provide instructions for postgres. In my opinion, it would be an omission not to include some example instructions.

**Comment by cnasikas** [comment]
> I'll add a note saying that any db works, but we provide instructions for postgres. In my opinion, it would be an omission not to include some example instructions.

Instructions is ok! I just think that the script should be as agnostic as possible.

**Comment by OrfeasLitos** [comment]
There's a tradeoff between the script being agnostic and the user having to understand too much to install. (The 3rd option is to use much more complex things on our side, but that's something I won't be able to do too soon.)

**Comment by OrfeasLitos** [comment]
I also annotated the code example to use javascript highlighting.

**Comment by cnasikas** [comment]
The "Homepage URL" and "Authorisation callback URL" is environment depended. As Decrypto we have different configuration for development and production.

**Develepment (blockchain-course-dev):**

Homepage URL: http://localhost:3001/

Authorisation callback URL: http://localhost:3000/api/auth/github/callback

**Production (blockchain-course):**

Homepage URL: https://blockchain-course.org

Authorisation callback URL: https://blockchain-course.org/api/auth/github/callback

The "Homepage URL" in installation instructions of step 2 for development environment is wrong. It must be http://localhost:3001/ (the default)

**Comment by gtklocker** [comment]
General comment: you can use git subtrees instead of submodules to avoid having the extra step

**Comment by OrfeasLitos** [comment]
Fixed

**Review by cnasikas — APPROVED** [review]

**Comment by cnasikas** [comment]
Nice! I really believe that the db creation command should not be part of the installation script. None of the big frameworks such us Django, Laravel, Ruby on Rails, WordPress etc do that. They create databases, tables etc but the framework is agnostic to the underlying database. Nevertheless, its a very good PR so if you want you can merge as it is.

**Comment by dionyziz** [comment]
FWIW I agree with @cnasikas on the point of database creation. The current system is DBMS-agnostic. If we make it possible to work with a stand-alone database environment (SQLite), then it would make sense to generate the database in the script. For now it's best if this is a separate command ran by the user.

However, I do understand the merit of putting it in, in terms of ease-of-use. In that case, we should at least *ask* the user if they're using Postgres and if they want the database with the particular name to be created for them.

**Comment by OrfeasLitos** [comment]
Removed db creation from script, gave generic & specific instructions in README.md

**Pull request merged**
